import type { KitDocument, Requirement } from '../domain/types';
import { buildSchedule } from '../schedule/allocator';

export interface RequirementReadiness {
  requirement_id: string;
  text: string;
  priority: Requirement['priority'];
  /** 0 (never practised or always "again") to 1 (consistently easy). */
  readiness: number;
  status: 'untouched' | 'shaky' | 'getting there' | 'solid';
  reviews: number;
  question_ids: string[];
  card_ids: string[];
}

export interface ReadinessReport {
  overall: number;
  must_ready: number;
  must_total: number;
  weakest: RequirementReadiness[];
  requirements: RequirementReadiness[];
}

/**
 * Readiness report (the custom feature).
 *
 * A prep kit tells you what to study; it does not tell you what you are still
 * bad at. This joins the two halves the app already has - which requirements a
 * card covers, and how confident the user felt about that card - into a per
 * requirement readiness score, so "you are not ready on the two must-haves
 * that carry the interview" is answerable rather than a feeling.
 *
 * The scoring is deliberately simple and explainable: the most recent
 * confidence for each card (1..4) maps to 0..1, a requirement scores the mean
 * of its cards, and anything never practised scores zero rather than being
 * quietly excluded. Nothing is generated by a model here.
 */
export function buildReadinessReport(document: KitDocument): ReadinessReport {
  const kit = document.kit;
  if (!kit) return { overall: 0, must_ready: 0, must_total: 0, weakest: [], requirements: [] };

  const latestByCard = new Map<string, { confidence: number; reps: number }>();
  for (const record of document.practice) {
    latestByCard.set(record.card_id, { confidence: record.confidence, reps: record.reps });
  }

  const requirements: RequirementReadiness[] = kit.role.requirements.map((requirement) => {
    const cards = kit.flashcards.filter((card) => card.requirement_ids.includes(requirement.id));
    const questions = kit.questions.filter((question) =>
      question.requirement_ids.includes(requirement.id),
    );
    const scores = cards
      .map((card) => latestByCard.get(card.id))
      .filter((entry): entry is { confidence: number; reps: number } => Boolean(entry))
      .map((entry) => (entry.confidence - 1) / 3);

    const readiness = scores.length === 0 ? 0 : scores.reduce((sum, value) => sum + value, 0) / scores.length;
    return {
      requirement_id: requirement.id,
      text: requirement.text,
      priority: requirement.priority,
      readiness: Number(readiness.toFixed(2)),
      status:
        scores.length === 0
          ? 'untouched'
          : readiness < 0.34
            ? 'shaky'
            : readiness < 0.67
              ? 'getting there'
              : 'solid',
      reviews: scores.length,
      question_ids: questions.map((question) => question.id),
      card_ids: cards.map((card) => card.id),
    };
  });

  const musts = requirements.filter((entry) => entry.priority === 'must');
  const overall =
    requirements.length === 0
      ? 0
      : requirements.reduce((sum, entry) => sum + entry.readiness, 0) / requirements.length;

  return {
    overall: Number(overall.toFixed(2)),
    must_ready: musts.filter((entry) => entry.readiness >= 0.67).length,
    must_total: musts.length,
    // Must-haves first, then whatever is least ready: the order you should
    // spend your remaining evenings in.
    weakest: [...requirements]
      .sort((a, b) => {
        if (a.priority !== b.priority) return a.priority === 'must' ? -1 : 1;
        return a.readiness - b.readiness;
      })
      .slice(0, 8),
    requirements,
  };
}

/**
 * Re-plans the days that are left, weighted by what practice says is weak.
 * The allocation itself is still the same deterministic allocator - only the
 * ordering weight changes - so every guarantee it makes still holds.
 */
export function replanSchedule(document: KitDocument, daysRemaining: number) {
  const kit = document.kit;
  if (!kit) throw new Error('nothing to re-plan');
  const report = buildReadinessReport(document);

  const weakness: Record<string, number> = {};
  for (const entry of report.requirements) {
    for (const questionId of entry.question_ids) {
      const priorityWeight = entry.priority === 'must' ? 1 : 0.5;
      weakness[questionId] = Math.max(
        weakness[questionId] ?? 0,
        (1 - entry.readiness) * priorityWeight,
      );
    }
  }

  return buildSchedule({
    daysAvailable: daysRemaining,
    questions: kit.questions,
    requirements: kit.role.requirements,
    weakness,
  });
}
